### ISSUE TITLE
Expected a color. Got: transparent while compiling mixins

### ISSUE THREAD

**Issue by osaris** [jlong/sass-bootstrap-defunct#47] opened 2012-12-13 14:16 UTC
I have this error while compiling mixins

```
Expected a color. Got: transparent
  (in /home/raphael/sites/ci.imagineapp.com/bennett/app/assets/stylesheets/application.css.sass)
/var/lib/gems/1.9.1/gems/bootstrap-sass-2.2.1.1/vendor/assets/stylesheets/bootstrap/_mixins.scss:457:in `gradient- striped'
```

Problem looks to be here :

https://github.com/jlong/sass-twitter-bootstrap/blob/master/lib/_mixins.scss#L443

**Comment by m5o** [comment] 2012-12-13 14:20
Which Sass version are you running?

**Comment by osaris** [comment] 2012-12-13 14:23
sass-3.2.3

**Comment by m5o** [comment] 2012-12-13 14:31
Sure? Your [Gemfile.lock](https://github.com/belighted/bennett/blob/master/Gemfile.lock#L159) referenced to 3.1.15

Please run `gem update sass` or `bundle update sass` I'm not sure which one is right.

**Comment by osaris** [comment] 2012-12-13 15:23
bennett isn't my project and I have updated gems locally, here are the gems installed :

```
hydrogen:/home/raphael/sites/ci.imagineapp.com/bennett$ gem list | grep sass
bootstrap-sass (2.2.1.1, 2.0.3)
sass (3.2.3)
sass-rails (3.2.5)
sass-rails-bootstrap (2.1.1)
```

**Comment by m5o** [comment] 2013-01-02 00:09
Can someone else reproduce this behaviour? in my senarios 'transparent' works well

**Comment by Shpigford** [comment] 2013-02-04 13:35
I'm also experiencing this exact issue.

**Comment by m5o** [comment] 2013-02-04 16:56
Is your setup definitely include sass (3.2)?

**Comment by Shpigford** [comment] 2013-02-05 12:32
@m50 Yes.

**Comment by brevity** [comment] 2013-04-10 17:01
You must also have compass installed. This issue is caused by the compass opacity mixin overriding the one declared at lib/_mixins.scss#L443.

Here's the Compass version http://compass-style.org/reference/compass/css3/opacity/

The Compass mixin expects "A number between 0 and 1, where 0 is transparent and 1 is opaque." Whereas our custom opacity mixin wants us to use a range from 0 to 100.

``` SASS
// lib/_mixins.css expects this
@include opacity(85);

//While Compass wants this
@include opacity(.85);

// Compass wins!

// Code Fails :-(

```

I'd suggest rewriting the custom mixin to fall inline with Compass, and just update the @includes in the bootstrap scss files. (there's only ten of them).

**Props jlong, this project's been pretty helpful introducing me Sass!**

**Comment by jlong** [comment] 2014-04-11 11:14
Closing as there is now an official Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass

**Closed as completed by jlong** 2014-04-11 11:14 UTC
